// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradingMicroservices.Services.PortfolioService.Data;

#nullable disable

namespace TradingMicroservices.Services.PortfolioService.Data.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20251001212323_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("portfolio")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Services.PortfolioService.Data.Entities.LastPrice", b =>
                {
                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StockId");

                    b.ToTable("last_prices", "portfolio");
                });

            modelBuilder.Entity("Services.PortfolioService.Data.Entities.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AvgPrice")
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("RealizedPnl")
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.HasIndex("UserRef", "StockId")
                        .IsUnique();

                    b.ToTable("positions", "portfolio");
                });

            modelBuilder.Entity("Services.PortfolioService.Data.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("stocks", "portfolio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apple Inc.",
                            Symbol = "AAPL"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tesla, Inc.",
                            Symbol = "TSLA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "NVIDIA Corporation",
                            Symbol = "NVDA"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Microsoft Corporation",
                            Symbol = "MSFT"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Amazon.com, Inc.",
                            Symbol = "AMZN"
                        });
                });

            modelBuilder.Entity("Services.PortfolioService.Data.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderRefId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<string>("UserRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("OrderRefId")
                        .IsUnique();

                    b.HasIndex("StockId");

                    b.HasIndex("UserRef", "StockId", "Date");

                    b.ToTable("trades", "portfolio");
                });

            modelBuilder.Entity("Services.PortfolioService.Data.Entities.LastPrice", b =>
                {
                    b.HasOne("Services.PortfolioService.Data.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Services.PortfolioService.Data.Entities.Position", b =>
                {
                    b.HasOne("Services.PortfolioService.Data.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Services.PortfolioService.Data.Entities.Trade", b =>
                {
                    b.HasOne("Services.PortfolioService.Data.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
